Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "dockerserver"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "dockerubuntu"
    vb.memory = "4096"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    # remove old docker packages if exists on the VM
    apt-get remove -y docker docker-engine docker.io containerd runc
    rm -rf /var/lib/docker/ 2>/dev/null
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
    apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
    docker --version
  SHELL
end